/* !!! Fichier à supprimer avant merge en master*/


/*Creation de la table box_catalog*/
CREATE TABLE `kameobiknq`.`boxes_catalog` ( `ID` INT(3) NOT NULL AUTO_INCREMENT , `HEU_MAJ` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , `USR_MAJ` VARCHAR(150) NULL , `MODEL` VARCHAR(50) NOT NULL , `PRODUCTION_PRICE` FLOAT NOT NULL , `INSTALLATION_PRICE` FLOAT NOT NULL , `LOCATION_PRICE` FLOAT NOT NULL , PRIMARY KEY (`ID`)) ENGINE = MyISAM;
/*Ajout de données*/
INSERT INTO `boxes_catalog` (`ID`, `HEU_MAJ`, `USR_MAJ`, `MODEL`, `PRODUCTION_PRICE`, `INSTALLATION_PRICE`, `LOCATION_PRICE`) VALUES (NULL, CURRENT_TIMESTAMP, NULL, '5 Clés', '500', '500', '200'), (NULL, CURRENT_TIMESTAMP, NULL, '10 Clés', '700', '1000', '250'), (NULL, CURRENT_TIMESTAMP, NULL, '20 Clés', '900', '1500', '325')
